//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regensburger.RShare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_Core {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Core() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Regensburger.RShare.Properties.Resources.Core", typeof(Resources_Core).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added directory &quot;{0}&quot;.
        /// </summary>
        internal static string AddedDirectory {
            get {
                return ResourceManager.GetString("AddedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning of search database: Removed {0} of {1} entries..
        /// </summary>
        internal static string CleanSearchDatabase {
            get {
                return ResourceManager.GetString("CleanSearchDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At most {0} download(s) with {1} source(s) allowed….
        /// </summary>
        internal static string DownloadSourcesAllowed {
            get {
                return ResourceManager.GetString("DownloadSourcesAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown while writing the online signature!.
        /// </summary>
        internal static string Exception_OnlineSignature {
            get {
                return ResourceManager.GetString("Exception_OnlineSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework Version: {0}.
        /// </summary>
        internal static string NETFrameworkVersion {
            get {
                return ResourceManager.GetString("NETFrameworkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download of &quot;{0}&quot; could not be started because your hard disk drive does not contain enough space!.
        /// </summary>
        internal static string NoAvailableDiscSpace {
            get {
                return ResourceManager.GetString("NoAvailableDiscSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Version: {0}.
        /// </summary>
        internal static string OSVersion {
            get {
                return ResourceManager.GetString("OSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been loaded, connecting….
        /// </summary>
        internal static string StealthNetLoaded {
            get {
                return ResourceManager.GetString("StealthNetLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will be loaded.
        /// </summary>
        internal static string StealthNetLoading {
            get {
                return ResourceManager.GetString("StealthNetLoading", resourceCulture);
            }
        }
    }
}
