//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regensburger.RShare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Regensburger.RShare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap accessible_16x16 {
            get {
                object obj = ResourceManager.GetObject("accessible_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already {0} active searches!.
        /// </summary>
        internal static string AlreadyActiveSearches {
            get {
                return ResourceManager.GetString("AlreadyActiveSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A search with the pattern &quot;{0}&quot; already exists.\n\nIs to be searched again in the network?.
        /// </summary>
        internal static string AlreadySearchWithThisPattern {
            get {
                return ResourceManager.GetString("AlreadySearchWithThisPattern", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap application_lightning {
            get {
                object obj = ResourceManager.GetObject("application_lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_side_tree {
            get {
                object obj = ResourceManager.GetObject("application_side_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_xp {
            get {
                object obj = ResourceManager.GetObject("application_xp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_inout {
            get {
                object obj = ResourceManager.GetObject("arrow_inout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap building_go {
            get {
                object obj = ResourceManager.GetObject("building_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string CancelDownload {
            get {
                return ResourceManager.GetString("CancelDownload", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap closetotray_48x48 {
            get {
                object obj = ResourceManager.GetObject("closetotray_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connection_16x16 {
            get {
                object obj = ResourceManager.GetObject("connection_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections ({0}).
        /// </summary>
        internal static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap connections_16x16 {
            get {
                object obj = ResourceManager.GetObject("connections_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connections_24x24 {
            get {
                object obj = ResourceManager.GetObject("connections_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} D, {1:00}:{2:00}:{3:00}.
        /// </summary>
        internal static string Date_Diff {
            get {
                return ResourceManager.GetString("Date_Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} D.
        /// </summary>
        internal static string Date_Diff_Only_Days {
            get {
                return ResourceManager.GetString("Date_Diff_Only_Days", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap directories_16x16 {
            get {
                object obj = ResourceManager.GetObject("directories_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap directories_24x24 {
            get {
                object obj = ResourceManager.GetObject("directories_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap directory_16x16 {
            get {
                object obj = ResourceManager.GetObject("directory_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap directory_24x24 {
            get {
                object obj = ResourceManager.GetObject("directory_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap directory_add_16x16 {
            get {
                object obj = ResourceManager.GetObject("directory_add_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap directory_remove_16x16 {
            get {
                object obj = ResourceManager.GetObject("directory_remove_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap download_16x16 {
            get {
                object obj = ResourceManager.GetObject("download_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap download_24x24 {
            get {
                object obj = ResourceManager.GetObject("download_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queued.
        /// </summary>
        internal static string DownloadIsQueued {
            get {
                return ResourceManager.GetString("DownloadIsQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started.
        /// </summary>
        internal static string DownloadIsStarted {
            get {
                return ResourceManager.GetString("DownloadIsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads ({0} of {1}).
        /// </summary>
        internal static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap downstream_16x16 {
            get {
                object obj = ResourceManager.GetObject("downstream_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap downstream_limited_16x16 {
            get {
                object obj = ResourceManager.GetObject("downstream_limited_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error_16x16 {
            get {
                object obj = ResourceManager.GetObject("error_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_en_32x48 {
            get {
                object obj = ResourceManager.GetObject("flag_en_32x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_france_32x48 {
            get {
                object obj = ResourceManager.GetObject("flag_france_32x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_germany_32x48 {
            get {
                object obj = ResourceManager.GetObject("flag_germany_32x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_turkey_32x46 {
            get {
                object obj = ResourceManager.GetObject("flag_turkey_32x46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to close StealthNet, are you sure?.
        /// </summary>
        internal static string GoingToClose {
            get {
                return ResourceManager.GetString("GoingToClose", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap information_16x16 {
            get {
                object obj = ResourceManager.GetObject("information_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information_24x24 {
            get {
                object obj = ResourceManager.GetObject("information_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming/Outgoing connection established..
        /// </summary>
        internal static string InOutConnectionEstablished {
            get {
                return ResourceManager.GetString("InOutConnectionEstablished", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap misc_16x16 {
            get {
                object obj = ResourceManager.GetObject("misc_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.stealthnet.de/en_download.php.
        /// </summary>
        internal static string NewVersionDownloadLink {
            get {
                return ResourceManager.GetString("NewVersionDownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of StealthNet is available.\nWould you like to download it?.
        /// </summary>
        internal static string NewVersionMessage {
            get {
                return ResourceManager.GetString("NewVersionMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap next_24x24 {
            get {
                object obj = ResourceManager.GetObject("next_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection established. Connecting….
        /// </summary>
        internal static string NoConnectionEstablished {
            get {
                return ResourceManager.GetString("NoConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a preview player in the misc-settings first.
        /// </summary>
        internal static string noDefindedPreviewPlayer {
            get {
                return ResourceManager.GetString("noDefindedPreviewPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No needed sectors.
        /// </summary>
        internal static string NoNeededSectors {
            get {
                return ResourceManager.GetString("NoNeededSectors", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap notaccessible_16x16 {
            get {
                object obj = ResourceManager.GetObject("notaccessible_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Online Signature.
        /// </summary>
        internal static string OnlineSignatureActivation {
            get {
                return ResourceManager.GetString("OnlineSignatureActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing connection established. 
        ///Check Port forwarding for incoming connections!.
        /// </summary>
        internal static string OutConnectionEstablished {
            get {
                return ResourceManager.GetString("OutConnectionEstablished", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap peer_16x16 {
            get {
                object obj = ResourceManager.GetObject("peer_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap peer_24x24 {
            get {
                object obj = ResourceManager.GetObject("peer_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap peer0_16x16 {
            get {
                object obj = ResourceManager.GetObject("peer0_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap peer1_16x16 {
            get {
                object obj = ResourceManager.GetObject("peer1_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap peer2_16x16 {
            get {
                object obj = ResourceManager.GetObject("peer2_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap peer3_16x16 {
            get {
                object obj = ResourceManager.GetObject("peer3_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap peer4_16x16 {
            get {
                object obj = ResourceManager.GetObject("peer4_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap play_16x16 {
            get {
                object obj = ResourceManager.GetObject("play_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.stealthnet.de/en_porttest.php?port=.
        /// </summary>
        internal static string PortTestUrl {
            get {
                return ResourceManager.GetString("PortTestUrl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap preferences_16x16 {
            get {
                object obj = ResourceManager.GetObject("preferences_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preferences_24x24 {
            get {
                object obj = ResourceManager.GetObject("preferences_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap previous_24x24 {
            get {
                object obj = ResourceManager.GetObject("previous_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Info!.
        /// </summary>
        internal static string ProgressBar_NoInfo {
            get {
                return ResourceManager.GetString("ProgressBar_NoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Space!.
        /// </summary>
        internal static string ProgressBar_NoSpace {
            get {
                return ResourceManager.GetString("ProgressBar_NoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing….
        /// </summary>
        internal static string ProgressBar_Preparing {
            get {
                return ResourceManager.GetString("ProgressBar_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Filling….
        /// </summary>
        internal static string ProgressBar_ZeroFilling {
            get {
                return ResourceManager.GetString("ProgressBar_ZeroFilling", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rating0_16x16 {
            get {
                object obj = ResourceManager.GetObject("rating0_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rating1_16x16 {
            get {
                object obj = ResourceManager.GetObject("rating1_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rating2_16x16 {
            get {
                object obj = ResourceManager.GetObject("rating2_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rating3_16x16 {
            get {
                object obj = ResourceManager.GetObject("rating3_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh_16x16 {
            get {
                object obj = ResourceManager.GetObject("refresh_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap remove_16x16 {
            get {
                object obj = ResourceManager.GetObject("remove_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should restart StealthNet to apply changes!.
        /// </summary>
        internal static string RestartAfterChanges {
            get {
                return ResourceManager.GetString("RestartAfterChanges", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap restore_16x16 {
            get {
                object obj = ResourceManager.GetObject("restore_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rshare_135x135 {
            get {
                object obj = ResourceManager.GetObject("rshare_135x135", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_16x16 {
            get {
                object obj = ResourceManager.GetObject("search_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_24x24 {
            get {
                object obj = ResourceManager.GetObject("search_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches ({0} of {1}).
        /// </summary>
        internal static string Searches {
            get {
                return ResourceManager.GetString("Searches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string SearchState_Active {
            get {
                return ResourceManager.GetString("SearchState_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive.
        /// </summary>
        internal static string SearchState_Passive {
            get {
                return ResourceManager.GetString("SearchState_Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Directories ({0}).
        /// </summary>
        internal static string SharedDirectories {
            get {
                return ResourceManager.GetString("SharedDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Files ({0} of {1}).
        /// </summary>
        internal static string SharedFiles {
            get {
                return ResourceManager.GetString("SharedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string SourceQueuePositionUnknown {
            get {
                return ResourceManager.GetString("SourceQueuePositionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string SourceState_Active {
            get {
                return ResourceManager.GetString("SourceState_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not needed.
        /// </summary>
        internal static string SourceState_NotNeeded {
            get {
                return ResourceManager.GetString("SourceState_NotNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        internal static string SourceState_Requested {
            get {
                return ResourceManager.GetString("SourceState_Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting.
        /// </summary>
        internal static string SourceState_Requesting {
            get {
                return ResourceManager.GetString("SourceState_Requesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        internal static string SourceState_Verified {
            get {
                return ResourceManager.GetString("SourceState_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying.
        /// </summary>
        internal static string SourceState_Verifying {
            get {
                return ResourceManager.GetString("SourceState_Verifying", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap splashscreenStealthNet {
            get {
                object obj = ResourceManager.GetObject("splashscreenStealthNet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap statistics_24x24 {
            get {
                object obj = ResourceManager.GetObject("statistics_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string Statistics_Average {
            get {
                return ResourceManager.GetString("Statistics_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average (1 Minute).
        /// </summary>
        internal static string Statistics_Average1Minute {
            get {
                return ResourceManager.GetString("Statistics_Average1Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections: {0}.
        /// </summary>
        internal static string Statistics_Connections {
            get {
                return ResourceManager.GetString("Statistics_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of Downloads: {0}.
        /// </summary>
        internal static string Statistics_CountDownloads {
            get {
                return ResourceManager.GetString("Statistics_CountDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of Uploads: {0}.
        /// </summary>
        internal static string Statistics_CountUploads {
            get {
                return ResourceManager.GetString("Statistics_CountUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Statistics_Current {
            get {
                return ResourceManager.GetString("Statistics_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded: {0}.
        /// </summary>
        internal static string Statistics_Downloaded {
            get {
                return ResourceManager.GetString("Statistics_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries: {0}.
        /// </summary>
        internal static string Statistics_SearchDBEntries {
            get {
                return ResourceManager.GetString("Statistics_SearchDBEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filesize: {0}.
        /// </summary>
        internal static string Statistics_SearchDBFileSize {
            get {
                return ResourceManager.GetString("Statistics_SearchDBFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data volume: {0}.
        /// </summary>
        internal static string Statistics_SearchDBFileSizeOfEntries {
            get {
                return ResourceManager.GetString("Statistics_SearchDBFileSizeOfEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last CleanUp: {0}.
        /// </summary>
        internal static string Statistics_SearchDBLastCleanUp {
            get {
                return ResourceManager.GetString("Statistics_SearchDBLastCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries removed: {0}.
        /// </summary>
        internal static string Statistics_SearchDBLastCleanUpCount {
            get {
                return ResourceManager.GetString("Statistics_SearchDBLastCleanUpCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded: {0}.
        /// </summary>
        internal static string Statistics_Uploaded {
            get {
                return ResourceManager.GetString("Statistics_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime: {0} days, {1} hours, {2} minutes, {3} seconds.
        /// </summary>
        internal static string Statistics_Uptime {
            get {
                return ResourceManager.GetString("Statistics_Uptime", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap StealthNet {
            get {
                object obj = ResourceManager.GetObject("StealthNet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stealthnet_135x135 {
            get {
                object obj = ResourceManager.GetObject("stealthnet_135x135", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StealthNet {0} is closing….
        /// </summary>
        internal static string StealthNetIsClosing {
            get {
                return ResourceManager.GetString("StealthNetIsClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StealthNet {0} is loading….
        /// </summary>
        internal static string StealthNetIsLoading {
            get {
                return ResourceManager.GetString("StealthNetIsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarming.
        /// </summary>
        internal static string Swarming {
            get {
                return ResourceManager.GetString("Swarming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         Database results {0} of {1}. Please use a more specific search pattern..
        /// </summary>
        internal static string TooManySearchDBResults {
            get {
                return ResourceManager.GetString("TooManySearchDBResults", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap upload_16x16 {
            get {
                object obj = ResourceManager.GetObject("upload_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upload_24x24 {
            get {
                object obj = ResourceManager.GetObject("upload_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploads ({0} of {1}), On Queue: {2}.
        /// </summary>
        internal static string Uploads {
            get {
                return ResourceManager.GetString("Uploads", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap upstream_16x16 {
            get {
                object obj = ResourceManager.GetObject("upstream_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upstream_limited_16x16 {
            get {
                object obj = ResourceManager.GetObject("upstream_limited_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning_16x16 {
            get {
                object obj = ResourceManager.GetObject("warning_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap worldaccessible_16x16 {
            get {
                object obj = ResourceManager.GetObject("worldaccessible_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom {
            get {
                object obj = ResourceManager.GetObject("zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_in {
            get {
                object obj = ResourceManager.GetObject("zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
