//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regensburger.RShare.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("corrupt")]
        public string CorruptDirectory {
            get {
                return ((string)(this["CorruptDirectory"]));
            }
            set {
                this["CorruptDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("incoming")]
        public string IncomingDirectory {
            get {
                return ((string)(this["IncomingDirectory"]));
            }
            set {
                this["IncomingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("log")]
        public string LogDirectory {
            get {
                return ((string)(this["LogDirectory"]));
            }
            set {
                this["LogDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("preferences")]
        public string PreferencesDirectory {
            get {
                return ((string)(this["PreferencesDirectory"]));
            }
            set {
                this["PreferencesDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("temp")]
        public string TemporaryDirectory {
            get {
                return ((string)(this["TemporaryDirectory"]));
            }
            set {
                this["TemporaryDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string UICulture {
            get {
                return ((string)(this["UICulture"]));
            }
            set {
                this["UICulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wmv|mov|asf|avi|mpeg|mpg|mp3|flac|ogg|wav|wma|divx|mp4|mkv")]
        public string PreviewFiletypes {
            get {
                return ((string)(this["PreviewFiletypes"]));
            }
            set {
                this["PreviewFiletypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviewPlayer {
            get {
                return ((string)(this["PreviewPlayer"]));
            }
            set {
                this["PreviewPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string AlwaysCloseToTray {
            get {
                return ((string)(this["AlwaysCloseToTray"]));
            }
            set {
                this["AlwaysCloseToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string AverageConnectionsCount {
            get {
                return ((string)(this["AverageConnectionsCount"]));
            }
            set {
                this["AverageConnectionsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("131072")]
        public string DownloadCapacity {
            get {
                return ((string)(this["DownloadCapacity"]));
            }
            set {
                this["DownloadCapacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string DownloadInformationDialogLastTab {
            get {
                return ((string)(this["DownloadInformationDialogLastTab"]));
            }
            set {
                this["DownloadInformationDialogLastTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65536")]
        public string DownloadLimit {
            get {
                return ((string)(this["DownloadLimit"]));
            }
            set {
                this["DownloadLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string FirstStart {
            get {
                return ((string)(this["FirstStart"]));
            }
            set {
                this["FirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string HasDownloadLimit {
            get {
                return ((string)(this["HasDownloadLimit"]));
            }
            set {
                this["HasDownloadLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string HasUploadLimit {
            get {
                return ((string)(this["HasUploadLimit"]));
            }
            set {
                this["HasUploadLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string MainFormLastTab {
            get {
                return ((string)(this["MainFormLastTab"]));
            }
            set {
                this["MainFormLastTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MainFormLocationX {
            get {
                return ((string)(this["MainFormLocationX"]));
            }
            set {
                this["MainFormLocationX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MainFormSizeWidth {
            get {
                return ((string)(this["MainFormSizeWidth"]));
            }
            set {
                this["MainFormSizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6097")]
        public string Port {
            get {
                return ((string)(this["Port"]));
            }
            set {
                this["Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string PreferencesDialogLastTab {
            get {
                return ((string)(this["PreferencesDialogLastTab"]));
            }
            set {
                this["PreferencesDialogLastTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ProgressBarsHaveShadow {
            get {
                return ((string)(this["ProgressBarsHaveShadow"]));
            }
            set {
                this["ProgressBarsHaveShadow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string ProgressBarsShadow {
            get {
                return ((string)(this["ProgressBarsShadow"]));
            }
            set {
                this["ProgressBarsShadow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string ProgressBarsShowPercent {
            get {
                return ((string)(this["ProgressBarsShowPercent"]));
            }
            set {
                this["ProgressBarsShowPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string SearchResultInformationDialogLastTab {
            get {
                return ((string)(this["SearchResultInformationDialogLastTab"]));
            }
            set {
                this["SearchResultInformationDialogLastTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ShowMessageBoxes {
            get {
                return ((string)(this["ShowMessageBoxes"]));
            }
            set {
                this["ShowMessageBoxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string SynchronizeWebCaches {
            get {
                return ((string)(this["SynchronizeWebCaches"]));
            }
            set {
                this["SynchronizeWebCaches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16384")]
        public string UploadCapacity {
            get {
                return ((string)(this["UploadCapacity"]));
            }
            set {
                this["UploadCapacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8192")]
        public string UploadLimit {
            get {
                return ((string)(this["UploadLimit"]));
            }
            set {
                this["UploadLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string UseBytesInsteadOfBits {
            get {
                return ((string)(this["UseBytesInsteadOfBits"]));
            }
            set {
                this["UseBytesInsteadOfBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string UserWasAsked {
            get {
                return ((string)(this["UserWasAsked"]));
            }
            set {
                this["UserWasAsked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string AutoReloadSharedFiles {
            get {
                return ((string)(this["AutoReloadSharedFiles"]));
            }
            set {
                this["AutoReloadSharedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string AutoReloadSharedFilesPause {
            get {
                return ((string)(this["AutoReloadSharedFilesPause"]));
            }
            set {
                this["AutoReloadSharedFilesPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string WriteLogfile {
            get {
                return ((string)(this["WriteLogfile"]));
            }
            set {
                this["WriteLogfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MainFormLocationY {
            get {
                return ((string)(this["MainFormLocationY"]));
            }
            set {
                this["MainFormLocationY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MainFormSizeHeight {
            get {
                return ((string)(this["MainFormSizeHeight"]));
            }
            set {
                this["MainFormSizeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string ActivateOnlineSignature {
            get {
                return ((string)(this["ActivateOnlineSignature"]));
            }
            set {
                this["ActivateOnlineSignature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string OnlineSignatureUpdateIntervall {
            get {
                return ((string)(this["OnlineSignatureUpdateIntervall"]));
            }
            set {
                this["OnlineSignatureUpdateIntervall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ParseCollections {
            get {
                return ((string)(this["ParseCollections"]));
            }
            set {
                this["ParseCollections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string SubFoldersForCollections {
            get {
                return ((string)(this["SubFoldersForCollections"]));
            }
            set {
                this["SubFoldersForCollections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string AutoMoveDownloads {
            get {
                return ((string)(this["AutoMoveDownloads"]));
            }
            set {
                this["AutoMoveDownloads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string AutoMoveDownloadsIntervall {
            get {
                return ((string)(this["AutoMoveDownloadsIntervall"]));
            }
            set {
                this["AutoMoveDownloadsIntervall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string StartInTray {
            get {
                return ((string)(this["StartInTray"]));
            }
            set {
                this["StartInTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string NewDownloadsToBeginngingOfQueue {
            get {
                return ((string)(this["NewDownloadsToBeginngingOfQueue"]));
            }
            set {
                this["NewDownloadsToBeginngingOfQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string searchSplitterDistance {
            get {
                return ((string)(this["searchSplitterDistance"]));
            }
            set {
                this["searchSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string searchesPatternIndex {
            get {
                return ((string)(this["searchesPatternIndex"]));
            }
            set {
                this["searchesPatternIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string searchesPatternWidth {
            get {
                return ((string)(this["searchesPatternWidth"]));
            }
            set {
                this["searchesPatternWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string searchesIsActiveIndex {
            get {
                return ((string)(this["searchesIsActiveIndex"]));
            }
            set {
                this["searchesIsActiveIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string searchesIsActiveWidth {
            get {
                return ((string)(this["searchesIsActiveWidth"]));
            }
            set {
                this["searchesIsActiveWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string searchesResultsIndex {
            get {
                return ((string)(this["searchesResultsIndex"]));
            }
            set {
                this["searchesResultsIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string searchesResultsWidth {
            get {
                return ((string)(this["searchesResultsWidth"]));
            }
            set {
                this["searchesResultsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string resultsIconIndex {
            get {
                return ((string)(this["resultsIconIndex"]));
            }
            set {
                this["resultsIconIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string resultsIconWidth {
            get {
                return ((string)(this["resultsIconWidth"]));
            }
            set {
                this["resultsIconWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string resultsRatingIconIndex {
            get {
                return ((string)(this["resultsRatingIconIndex"]));
            }
            set {
                this["resultsRatingIconIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string resultsRatingIconWidth {
            get {
                return ((string)(this["resultsRatingIconWidth"]));
            }
            set {
                this["resultsRatingIconWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string resultsFileNameIndex {
            get {
                return ((string)(this["resultsFileNameIndex"]));
            }
            set {
                this["resultsFileNameIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string resultsFileNameWidth {
            get {
                return ((string)(this["resultsFileNameWidth"]));
            }
            set {
                this["resultsFileNameWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string resultsFileSizeIndex {
            get {
                return ((string)(this["resultsFileSizeIndex"]));
            }
            set {
                this["resultsFileSizeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string resultsFileSizeWidth {
            get {
                return ((string)(this["resultsFileSizeWidth"]));
            }
            set {
                this["resultsFileSizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string resultsSourcesIndex {
            get {
                return ((string)(this["resultsSourcesIndex"]));
            }
            set {
                this["resultsSourcesIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string resultsSourcesWidth {
            get {
                return ((string)(this["resultsSourcesWidth"]));
            }
            set {
                this["resultsSourcesWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string resultsAlbumIndex {
            get {
                return ((string)(this["resultsAlbumIndex"]));
            }
            set {
                this["resultsAlbumIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string resultsAlbumWidth {
            get {
                return ((string)(this["resultsAlbumWidth"]));
            }
            set {
                this["resultsAlbumWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string resultsArtistIndex {
            get {
                return ((string)(this["resultsArtistIndex"]));
            }
            set {
                this["resultsArtistIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string resultsArtistWidth {
            get {
                return ((string)(this["resultsArtistWidth"]));
            }
            set {
                this["resultsArtistWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string resultsTitleIndex {
            get {
                return ((string)(this["resultsTitleIndex"]));
            }
            set {
                this["resultsTitleIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string resultsTitleWidth {
            get {
                return ((string)(this["resultsTitleWidth"]));
            }
            set {
                this["resultsTitleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string sharedIconIndex {
            get {
                return ((string)(this["sharedIconIndex"]));
            }
            set {
                this["sharedIconIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string sharedIconWidth {
            get {
                return ((string)(this["sharedIconWidth"]));
            }
            set {
                this["sharedIconWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string sharedRatingIconIndex {
            get {
                return ((string)(this["sharedRatingIconIndex"]));
            }
            set {
                this["sharedRatingIconIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string sharedRatingIconWidth {
            get {
                return ((string)(this["sharedRatingIconWidth"]));
            }
            set {
                this["sharedRatingIconWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string sharedFileNameIndex {
            get {
                return ((string)(this["sharedFileNameIndex"]));
            }
            set {
                this["sharedFileNameIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string sharedFileNameWidth {
            get {
                return ((string)(this["sharedFileNameWidth"]));
            }
            set {
                this["sharedFileNameWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string sharedFileSizeIndex {
            get {
                return ((string)(this["sharedFileSizeIndex"]));
            }
            set {
                this["sharedFileSizeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string sharedFileSizeWidth {
            get {
                return ((string)(this["sharedFileSizeWidth"]));
            }
            set {
                this["sharedFileSizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string sharedDirectoryIndex {
            get {
                return ((string)(this["sharedDirectoryIndex"]));
            }
            set {
                this["sharedDirectoryIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string sharedDirectoryWidth {
            get {
                return ((string)(this["sharedDirectoryWidth"]));
            }
            set {
                this["sharedDirectoryWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string sharedAlbumIndex {
            get {
                return ((string)(this["sharedAlbumIndex"]));
            }
            set {
                this["sharedAlbumIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string sharedAlbumWidth {
            get {
                return ((string)(this["sharedAlbumWidth"]));
            }
            set {
                this["sharedAlbumWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string sharedArtistIndex {
            get {
                return ((string)(this["sharedArtistIndex"]));
            }
            set {
                this["sharedArtistIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string sharedArtistWidth {
            get {
                return ((string)(this["sharedArtistWidth"]));
            }
            set {
                this["sharedArtistWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string sharedTitleIndex {
            get {
                return ((string)(this["sharedTitleIndex"]));
            }
            set {
                this["sharedTitleIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string sharedTitleWidth {
            get {
                return ((string)(this["sharedTitleWidth"]));
            }
            set {
                this["sharedTitleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string sharedlastRequestIndex {
            get {
                return ((string)(this["sharedlastRequestIndex"]));
            }
            set {
                this["sharedlastRequestIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string sharedlastRequestWidth {
            get {
                return ((string)(this["sharedlastRequestWidth"]));
            }
            set {
                this["sharedlastRequestWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string uploadsFileNameIndex {
            get {
                return ((string)(this["uploadsFileNameIndex"]));
            }
            set {
                this["uploadsFileNameIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string uploadsFileNameWidth {
            get {
                return ((string)(this["uploadsFileNameWidth"]));
            }
            set {
                this["uploadsFileNameWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string uploadsFileSizeIndex {
            get {
                return ((string)(this["uploadsFileSizeIndex"]));
            }
            set {
                this["uploadsFileSizeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string uploadsFileSizeWidth {
            get {
                return ((string)(this["uploadsFileSizeWidth"]));
            }
            set {
                this["uploadsFileSizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string uploadsCompletedIndex {
            get {
                return ((string)(this["uploadsCompletedIndex"]));
            }
            set {
                this["uploadsCompletedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string uploadsCompletedWidth {
            get {
                return ((string)(this["uploadsCompletedWidth"]));
            }
            set {
                this["uploadsCompletedWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string uploadsProgressIndex {
            get {
                return ((string)(this["uploadsProgressIndex"]));
            }
            set {
                this["uploadsProgressIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string uploadsProgressWidth {
            get {
                return ((string)(this["uploadsProgressWidth"]));
            }
            set {
                this["uploadsProgressWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string uploadsRemainingIndex {
            get {
                return ((string)(this["uploadsRemainingIndex"]));
            }
            set {
                this["uploadsRemainingIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string uploadsRemainingWidth {
            get {
                return ((string)(this["uploadsRemainingWidth"]));
            }
            set {
                this["uploadsRemainingWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string uploadslastRequestIndex {
            get {
                return ((string)(this["uploadslastRequestIndex"]));
            }
            set {
                this["uploadslastRequestIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string uploadslastRequestWidth {
            get {
                return ((string)(this["uploadslastRequestWidth"]));
            }
            set {
                this["uploadslastRequestWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string connectionsIconIndex {
            get {
                return ((string)(this["connectionsIconIndex"]));
            }
            set {
                this["connectionsIconIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string connectionsIconWidth {
            get {
                return ((string)(this["connectionsIconWidth"]));
            }
            set {
                this["connectionsIconWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string connectionsIPAddressIndex {
            get {
                return ((string)(this["connectionsIPAddressIndex"]));
            }
            set {
                this["connectionsIPAddressIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("84,07821")]
        public string connectionsIPAddressWidth {
            get {
                return ((string)(this["connectionsIPAddressWidth"]));
            }
            set {
                this["connectionsIPAddressWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string connectionsPortIndex {
            get {
                return ((string)(this["connectionsPortIndex"]));
            }
            set {
                this["connectionsPortIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("84,07821")]
        public string connectionsPortWidth {
            get {
                return ((string)(this["connectionsPortWidth"]));
            }
            set {
                this["connectionsPortWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string connectionsSentIndex {
            get {
                return ((string)(this["connectionsSentIndex"]));
            }
            set {
                this["connectionsSentIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("84,07821")]
        public string connectionsSentWidth {
            get {
                return ((string)(this["connectionsSentWidth"]));
            }
            set {
                this["connectionsSentWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string connectionsReceivedIndex {
            get {
                return ((string)(this["connectionsReceivedIndex"]));
            }
            set {
                this["connectionsReceivedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("84,07821")]
        public string connectionsReceivedWidth {
            get {
                return ((string)(this["connectionsReceivedWidth"]));
            }
            set {
                this["connectionsReceivedWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string connectionsSentCommandsIndex {
            get {
                return ((string)(this["connectionsSentCommandsIndex"]));
            }
            set {
                this["connectionsSentCommandsIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("84,07821")]
        public string connectionsSentCommandsWidth {
            get {
                return ((string)(this["connectionsSentCommandsWidth"]));
            }
            set {
                this["connectionsSentCommandsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string connectionsReceivedCommandsIndex {
            get {
                return ((string)(this["connectionsReceivedCommandsIndex"]));
            }
            set {
                this["connectionsReceivedCommandsIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("84,07821")]
        public string connectionsReceivedCommandsWidth {
            get {
                return ((string)(this["connectionsReceivedCommandsWidth"]));
            }
            set {
                this["connectionsReceivedCommandsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string connectionsEnqueuedCommandsIndex {
            get {
                return ((string)(this["connectionsEnqueuedCommandsIndex"]));
            }
            set {
                this["connectionsEnqueuedCommandsIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("84,07821")]
        public string connectionsEnqueuedCommandsWidth {
            get {
                return ((string)(this["connectionsEnqueuedCommandsWidth"]));
            }
            set {
                this["connectionsEnqueuedCommandsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("67")]
        public string downloadsSplitterDistance {
            get {
                return ((string)(this["downloadsSplitterDistance"]));
            }
            set {
                this["downloadsSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string downloadsDownloadIconIndex {
            get {
                return ((string)(this["downloadsDownloadIconIndex"]));
            }
            set {
                this["downloadsDownloadIconIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string downloadsDownloadIconWidth {
            get {
                return ((string)(this["downloadsDownloadIconWidth"]));
            }
            set {
                this["downloadsDownloadIconWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string downloadsRatingIconIndex {
            get {
                return ((string)(this["downloadsRatingIconIndex"]));
            }
            set {
                this["downloadsRatingIconIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string downloadsRatingIconWidth {
            get {
                return ((string)(this["downloadsRatingIconWidth"]));
            }
            set {
                this["downloadsRatingIconWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string downloadsFileNameIndex {
            get {
                return ((string)(this["downloadsFileNameIndex"]));
            }
            set {
                this["downloadsFileNameIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string downloadsFileNameWidth {
            get {
                return ((string)(this["downloadsFileNameWidth"]));
            }
            set {
                this["downloadsFileNameWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string downloadsFileSizeIndex {
            get {
                return ((string)(this["downloadsFileSizeIndex"]));
            }
            set {
                this["downloadsFileSizeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string downloadsFileSizeWidth {
            get {
                return ((string)(this["downloadsFileSizeWidth"]));
            }
            set {
                this["downloadsFileSizeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string downloadsCompletedIndex {
            get {
                return ((string)(this["downloadsCompletedIndex"]));
            }
            set {
                this["downloadsCompletedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string downloadsCompletedWidth {
            get {
                return ((string)(this["downloadsCompletedWidth"]));
            }
            set {
                this["downloadsCompletedWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string downloadsProgressImageIndex {
            get {
                return ((string)(this["downloadsProgressImageIndex"]));
            }
            set {
                this["downloadsProgressImageIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public string downloadsProgressImageWidth {
            get {
                return ((string)(this["downloadsProgressImageWidth"]));
            }
            set {
                this["downloadsProgressImageWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string downloadsStatusIndex {
            get {
                return ((string)(this["downloadsStatusIndex"]));
            }
            set {
                this["downloadsStatusIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string downloadsStatusWidth {
            get {
                return ((string)(this["downloadsStatusWidth"]));
            }
            set {
                this["downloadsStatusWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string downloadsSourcesIndex {
            get {
                return ((string)(this["downloadsSourcesIndex"]));
            }
            set {
                this["downloadsSourcesIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string downloadsSourcesWidth {
            get {
                return ((string)(this["downloadsSourcesWidth"]));
            }
            set {
                this["downloadsSourcesWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string downloadsRemainingIndex {
            get {
                return ((string)(this["downloadsRemainingIndex"]));
            }
            set {
                this["downloadsRemainingIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string downloadsRemainingWidth {
            get {
                return ((string)(this["downloadsRemainingWidth"]));
            }
            set {
                this["downloadsRemainingWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public string downloadslastSeenIndex {
            get {
                return ((string)(this["downloadslastSeenIndex"]));
            }
            set {
                this["downloadslastSeenIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public string downloadslastSeenWidth {
            get {
                return ((string)(this["downloadslastSeenWidth"]));
            }
            set {
                this["downloadslastSeenWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string downloadslastReceptionIndex {
            get {
                return ((string)(this["downloadslastReceptionIndex"]));
            }
            set {
                this["downloadslastReceptionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public string downloadslastReceptionWidth {
            get {
                return ((string)(this["downloadslastReceptionWidth"]));
            }
            set {
                this["downloadslastReceptionWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string sourcesSourceIconIndex {
            get {
                return ((string)(this["sourcesSourceIconIndex"]));
            }
            set {
                this["sourcesSourceIconIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string sourcesSourceIconWidth {
            get {
                return ((string)(this["sourcesSourceIconWidth"]));
            }
            set {
                this["sourcesSourceIconWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string sourcesTypeIconIndex {
            get {
                return ((string)(this["sourcesTypeIconIndex"]));
            }
            set {
                this["sourcesTypeIconIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string sourcesTypeIconWidth {
            get {
                return ((string)(this["sourcesTypeIconWidth"]));
            }
            set {
                this["sourcesTypeIconWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string sourcesTypeIndex {
            get {
                return ((string)(this["sourcesTypeIndex"]));
            }
            set {
                this["sourcesTypeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string sourcesTypeWidth {
            get {
                return ((string)(this["sourcesTypeWidth"]));
            }
            set {
                this["sourcesTypeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string sourcesQueueIndex {
            get {
                return ((string)(this["sourcesQueueIndex"]));
            }
            set {
                this["sourcesQueueIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string sourcesQueueWidth {
            get {
                return ((string)(this["sourcesQueueWidth"]));
            }
            set {
                this["sourcesQueueWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string sourcesSentCommandsIndex {
            get {
                return ((string)(this["sourcesSentCommandsIndex"]));
            }
            set {
                this["sourcesSentCommandsIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string sourcesSentCommandsWidth {
            get {
                return ((string)(this["sourcesSentCommandsWidth"]));
            }
            set {
                this["sourcesSentCommandsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string sourcesReceivedCommandsIndex {
            get {
                return ((string)(this["sourcesReceivedCommandsIndex"]));
            }
            set {
                this["sourcesReceivedCommandsIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string sourcesReceivedCommandsWidth {
            get {
                return ((string)(this["sourcesReceivedCommandsWidth"]));
            }
            set {
                this["sourcesReceivedCommandsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string ActivateSearchDB {
            get {
                return ((string)(this["ActivateSearchDB"]));
            }
            set {
                this["ActivateSearchDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string SearchDBCleanUpDays {
            get {
                return ((string)(this["SearchDBCleanUpDays"]));
            }
            set {
                this["SearchDBCleanUpDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string resultsAgeIndex {
            get {
                return ((string)(this["resultsAgeIndex"]));
            }
            set {
                this["resultsAgeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string resultsAgeWidth {
            get {
                return ((string)(this["resultsAgeWidth"]));
            }
            set {
                this["resultsAgeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string MaxSearchDBResults {
            get {
                return ((string)(this["MaxSearchDBResults"]));
            }
            set {
                this["MaxSearchDBResults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string sourcesProgressIndex {
            get {
                return ((string)(this["sourcesProgressIndex"]));
            }
            set {
                this["sourcesProgressIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public string sourcesProgressWidth {
            get {
                return ((string)(this["sourcesProgressWidth"]));
            }
            set {
                this["sourcesProgressWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string MainFormWindowState {
            get {
                return ((string)(this["MainFormWindowState"]));
            }
            set {
                this["MainFormWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string MaximumDownloadsCount {
            get {
                return ((string)(this["MaximumDownloadsCount"]));
            }
            set {
                this["MaximumDownloadsCount"] = value;
            }
        }
    }
}
